#cloud-config
users:
  - default
  - name: runner
    groups: [sudo]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    system: true

write_files:
  - path: /opt/runner-hooks/idle/10-set-actions-runner-state
    owner: 'root:root'
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "idle" > /tmp/actions-runner-state
  - path: /opt/runner-hooks/job-started/10-set-actions-runner-state
    owner: 'root:root'
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "active" > /tmp/actions-runner-state
  - path: /opt/runner-hooks/job-started.sh
    owner: 'root:root'
    permissions: '0755'
    content: |
      #!/bin/bash
      /usr/bin/run-parts /opt/runner-hooks/job-started
  - path: /opt/actions.runner.service.template
    owner: 'root:root'
    permissions: '0644'
    content: |
      [Unit]
      Description={{Description}}
      After=network.target

      [Service]
      ExecStart={{RunnerRoot}}/runsvc.sh
      ExecStartPost=/usr/bin/run-parts /opt/runner-hooks/idle
      ExecStopPost=/usr/bin/sudo /usr/sbin/poweroff
      User={{User}}
      WorkingDirectory={{RunnerRoot}}
      Environment=ACTIONS_RUNNER_HOOK_JOB_STARTED=/opt/runner-hooks/job-started.sh
      KillMode=process
      KillSignal=SIGTERM
      TimeoutStopSec=5min

      [Install]
      WantedBy=multi-user.target
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable docker
  - mkdir -p /home/runner/actions-runner
  - cd /home/runner/actions-runner
  - |
    ARCH=$(uname -m)
    if [ "$ARCH" = "x86_64" ]; then
      ARCH="x64"
    elif [ "$ARCH" = "aarch64" ]; then
      ARCH="arm64"
    else
      echo "Unsupported architecture: $ARCH"
      exit 1
    fi
    curl -o actions-runner-linux.tar.gz -L https://github.com/actions/runner/releases/download/v{{RUNNER_VERSION}}/actions-runner-linux-${ARCH}-{{RUNNER_VERSION}}.tar.gz
  - tar xzf actions-runner-linux.tar.gz
  - rm actions-runner-linux.tar.gz
  - ./bin/installdependencies.sh
  - chown -R runner:runner /home/runner/actions-runner

power_state:
  delay: now
  mode: poweroff
  condition: true